<?php

namespace Database\Seeders;

use App\Models\Flag;
use Illuminate\Database\Seeder;

class FlagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $availableTags = [
            ['Andorra', 'AD', 'https://www.countryflags.io/AD/flat/24.png'],
            ['Andorra', 'AD', 'https://www.countryflags.io/AD/flat/24.png'],
            ['United Arab Emirates', 'AE', 'https://www.countryflags.io/AE/flat/24.png'],
            ['Afghanistan', 'AF', 'https://www.countryflags.io/AF/flat/24.png'],
            ['Antigua and Barbuda', 'AG', 'https://www.countryflags.io/AG/flat/24.png'],
            ['Anguilla', 'AI', 'https://www.countryflags.io/AI/flat/24.png'],
            ['', 'AH', 'https://www.countryflags.io/AH/flat/24.png'],
            ['', 'AK', 'https://www.countryflags.io/AK/flat/24.png'],
            ['Albania', 'AL', 'https://www.countryflags.io/AL/flat/24.png'],
            ['Armenia', 'AM', 'https://www.countryflags.io/AM/flat/24.png'],
            ['Netherlands Antilles', 'AN', 'https://www.countryflags.io/AN/flat/24.png'],
            ['Angola', 'AO', 'https://www.countryflags.io/AO/flat/24.png'],
            ['Antarctica', 'AQ', 'https://www.countryflags.io/AQ/flat/24.png'],
            ['Argentina', 'AR', 'https://www.countryflags.io/AR/flat/24.png'],
            ['American Samoa', 'AS', 'https://www.countryflags.io/AS/flat/24.png'],
            ['Austria', 'AT', 'https://www.countryflags.io/AT/flat/24.png'],
            ['Australia', 'AU', 'https://www.countryflags.io/AU/flat/24.png'],
            ['Aruba', 'AW', 'https://www.countryflags.io/AW/flat/24.png'],
            ['Åland Islands', 'AX', 'https://www.countryflags.io/AX/flat/24.png'],
            ['Azerbaijan', 'AZ', 'https://www.countryflags.io/AZ/flat/24.png'],
            ['Bosnia and Herzegovina', 'BA', 'https://www.countryflags.io/BA/flat/24.png'],
            ['Barbados', 'BB', 'https://www.countryflags.io/BB/flat/24.png'],
            ['Bangladesh', 'BD', 'https://www.countryflags.io/BD/flat/24.png'],
            ['Belgium', 'BE', 'https://www.countryflags.io/BE/flat/24.png'],
            ['Burkina Faso', 'BF', 'https://www.countryflags.io/BF/flat/24.png'],
            ['Bulgaria', 'BG', 'https://www.countryflags.io/BG/flat/24.png'],
            ['Bahrain', 'BH', 'https://www.countryflags.io/BH/flat/24.png'],
            ['Burundi', 'BI', 'https://www.countryflags.io/BI/flat/24.png'],
            ['Benin', 'BJ', 'https://www.countryflags.io/BJ/flat/24.png'],
            ['Saint Barthélemy', 'BL', 'https://www.countryflags.io/BL/flat/24.png'],
            ['Bermuda', 'BM', 'https://www.countryflags.io/BM/flat/24.png'],

            ['Brunei Darussalam', 'BN', 'https://www.countryflags.io/BN/flat/24.png'],
            ['Bolivia', 'BO', 'https://www.countryflags.io/BO/flat/24.png'],
            ['Bonaire, Sint Eustatius and Saba', 'BQ', 'https://www.countryflags.io/BQ/flat/24.png'],
            ['Brazil', 'BR', 'https://www.countryflags.io/BR/flat/24.png'],
            ['Bahamas', 'BS', 'https://www.countryflags.io/BS/flat/24.png'],
            ['Bhutan', 'BT', 'https://www.countryflags.io/BT/flat/24.png'],
            ['Bouvet Island', 'BV', 'https://www.countryflags.io/BV/flat/24.png'],
            ['Botswana', 'BW', 'https://www.countryflags.io/BW/flat/24.png'],
            ['Belarus', 'BY', 'https://www.countryflags.io/BY/flat/24.png'],
            ['Belize', 'BZ', 'https://www.countryflags.io/BZ/flat/24.png'],
            ['Canada', 'CA', 'https://www.countryflags.io/CA/flat/24.png'],
            ['Cocos (Keeling) Islands', 'CC', 'https://www.countryflags.io/CC/flat/24.png'],
            ['Congo, The Democratic Republic Of The', 'CD', 'https://www.countryflags.io/CD/flat/24.png'],
            ['Central African Republic', 'CF', 'https://www.countryflags.io/CF/flat/24.png'],
            ['Congo', 'CG', 'https://www.countryflags.io/CG/flat/24.png'],



            ['CH', 'CH', 'https://www.countryflags.io/CH/flat/24.png'],
            ['CI', 'CI', 'https://www.countryflags.io/CI/flat/24.png'],
            ['CK', 'CK', 'https://www.countryflags.io/CK/flat/24.png'],
            ['CL', 'CL', 'https://www.countryflags.io/CL/flat/24.png'],
            ['CM', 'CM', 'https://www.countryflags.io/CM/flat/24.png'],
            ['CN', 'CN', 'https://www.countryflags.io/CN/flat/24.png'],
            ['CO', 'CO', 'https://www.countryflags.io/CO/flat/24.png'],
            ['CR', 'CR', 'https://www.countryflags.io/CR/flat/24.png'],
            ['CU', 'CU', 'https://www.countryflags.io/CU/flat/24.png'],
            ['CV', 'CV', 'https://www.countryflags.io/CV/flat/24.png'],
            ['CW', 'CW', 'https://www.countryflags.io/CW/flat/24.png'],
            ['CX', 'CX', 'https://www.countryflags.io/CX/flat/24.png'],
            ['CY', 'CY', 'https://www.countryflags.io/CY/flat/24.png'],
            ['CZ', 'CZ', 'https://www.countryflags.io/CZ/flat/24.png'],
            ['DE', 'DE', 'https://www.countryflags.io/DE/flat/24.png'],
            ['DJ', 'DJ', 'https://www.countryflags.io/DJ/flat/24.png'],
            ['DK', 'DK', 'https://www.countryflags.io/DK/flat/24.png'],
            ['DM', 'DM', 'https://www.countryflags.io/DM/flat/24.png'],
            ['DO', 'DO', 'https://www.countryflags.io/DO/flat/24.png'],
            ['DZ', 'DZ', 'https://www.countryflags.io/DZ/flat/24.png'],
            ['EC', 'EC', 'https://www.countryflags.io/EC/flat/24.png'],
            ['EE', 'EE', 'https://www.countryflags.io/EE/flat/24.png'],
            ['EG', 'EG', 'https://www.countryflags.io/EG/flat/24.png'],
            ['EH', 'EH', 'https://www.countryflags.io/EH/flat/24.png'],
            ['ER', 'ER', 'https://www.countryflags.io/ER/flat/24.png'],
            ['ES', 'ES', 'https://www.countryflags.io/ES/flat/24.png'],
            ['ET', 'ET', 'https://www.countryflags.io/ET/flat/24.png'],
            ['', 'EU', 'https://www.countryflags.io/EU/flat/24.png'],


            ['Finland', 'FI', 'https://www.countryflags.io/FI/flat/24.png'],
            ['Fiji', 'FJ', 'https://www.countryflags.io/FJ/flat/24.png'],
            ['Falkland Islands (Malvinas)', 'FK', 'https://www.countryflags.io/FK/flat/24.png'],
            ['Micronesia, Federated States Of', 'FM', 'https://www.countryflags.io/FM/flat/24.png'],
            ['Faroe Islands', 'FO', 'https://www.countryflags.io/FO/flat/24.png'],
            ['France', 'FR', 'https://www.countryflags.io/FR/flat/24.png'],
            ['Gabon', 'GA', 'https://www.countryflags.io/GA/flat/24.png'],
            ['United Kingdom', 'GB', 'https://www.countryflags.io/GB/flat/24.png'],
            ['Grenada', 'GD', 'https://www.countryflags.io/GD/flat/24.png'],
            ['Georgia', 'GE', 'https://www.countryflags.io/GE/flat/24.png'],
            ['French Guiana', 'GF', 'https://www.countryflags.io/GF/flat/24.png'],
            ['Guernsey', 'GG', 'https://www.countryflags.io/GG/flat/24.png'],
            ['Ghana', 'GH', 'https://www.countryflags.io/GH/flat/24.png'],
            ['Gibraltar', 'GI', 'https://www.countryflags.io/GI/flat/24.png'],
            ['Greenland', 'GL', 'https://www.countryflags.io/GL/flat/24.png'],
            ['Gambia', 'GM', 'https://www.countryflags.io/GM/flat/24.png'],
            ['Guinea', 'GN', 'https://www.countryflags.io/GN/flat/24.png'],
            ['Guadeloupe', 'GP', 'https://www.countryflags.io/GP/flat/24.png'],
            ['Equatorial Guinea', 'GQ', 'https://www.countryflags.io/GQ/flat/24.png'],
            ['Greece', 'GR', 'https://www.countryflags.io/GR/flat/24.png'],
            ['South Georgia and the South Sandwich Islands', 'GS', 'https://www.countryflags.io/GS/flat/24.png'],
            ['Guatemala', 'GT', 'https://www.countryflags.io/GT/flat/24.png'],
            ['Guam', 'GU', 'https://www.countryflags.io/GU/flat/24.png'],
            ['Guinea-Bissau', 'GW', 'https://www.countryflags.io/GW/flat/24.png'],
            ['Guyana', 'GY', 'https://www.countryflags.io/GY/flat/24.png'],
            ['Hong Kong', 'HK', 'https://www.countryflags.io/HK/flat/24.png'],
            ['Heard and McDonald Islands', 'HM', 'https://www.countryflags.io/HM/flat/24.png'],
            ['Honduras', 'HN', 'https://www.countryflags.io/HN/flat/24.png'],
            ['Croatia', 'HR', 'https://www.countryflags.io/HR/flat/24.png'],
            ['Haiti', 'HT', 'https://www.countryflags.io/HT/flat/24.png'],
            ['Hungary', 'HU', 'https://www.countryflags.io/HU/flat/24.png'],
            ['', 'IC', 'https://www.countryflags.io/IC/flat/24.png'],


            ['Indonesia', 'AD', 'https://www.countryflags.io/ID/flat/24.png'],
            ['Ireland', 'AD', 'https://www.countryflags.io/IE/flat/24.png'],
            ['Israel', 'AD', 'https://www.countryflags.io/IL/flat/24.png'],
            ['Isle of Man', 'AD', 'https://www.countryflags.io/IM/flat/24.png'],
            ['India', 'AD', 'https://www.countryflags.io/IN/flat/24.png'],
            ['British Indian Ocean Territory', 'AD', 'https://www.countryflags.io/IO/flat/24.png'],
            ['Iraq', 'AD', 'https://www.countryflags.io/IQ/flat/24.png'],
            ['Iran, Islamic Republic Of', 'AD', 'https://www.countryflags.io/IR/flat/24.png'],
            ['Iceland', 'AD', 'https://www.countryflags.io/IS/flat/24.png'],
            ['Italy', 'AD', 'https://www.countryflags.io/IT/flat/24.png'],
            ['Jersey', 'AD', 'https://www.countryflags.io/JE/flat/24.png'],
            ['Jamaica', 'AD', 'https://www.countryflags.io/JM/flat/24.png'],
            ['Jordan', 'AD', 'https://www.countryflags.io/JO/flat/24.png'],
            ['Japan', 'AD', 'https://www.countryflags.io/JP/flat/24.png'],
            ['Kenya', 'AD', 'https://www.countryflags.io/KE/flat/24.png'],
            ['Kyrgyzstan', 'AD', 'https://www.countryflags.io/KG/flat/24.png'],
            ['Cambodia', 'AD', 'https://www.countryflags.io/KH/flat/24.png'],
            ['Kiribati', 'AD', 'https://www.countryflags.io/KI/flat/24.png'],
            ['Comoros', 'AD', 'https://www.countryflags.io/KM/flat/24.png'],
            ['Saint Kitts And Nevis', 'AD', 'https://www.countryflags.io/KN/flat/24.png'],
            ['Korea, Democratic Peoples Republic Of', 'AD', 'https://www.countryflags.io/KP/flat/24.png'],
            ['Korea, Republic of', 'AD', 'https://www.countryflags.io/KR/flat/24.png'],
            ['Kuwait', 'AD', 'https://www.countryflags.io/KW/flat/24.png'],
            ['Cayman Islands', 'AD', 'https://www.countryflags.io/KY/flat/24.png'],
            ['Kazakhstan', 'AD', 'https://www.countryflags.io/KZ/flat/24.png'],
            ['Lao Peoples Democratic Republic', 'AD', 'https://www.countryflags.io/LA/flat/24.png'],
            ['Lebanon', 'AD', 'https://www.countryflags.io/LB/flat/24.png'],
            ['Saint Lucia', 'AD', 'https://www.countryflags.io/LC/flat/24.png'],
            ['Liechtenstein', 'AD', 'https://www.countryflags.io/LI/flat/24.png'],
            ['Sri Lanka', 'AD', 'https://www.countryflags.io/LK/flat/24.png'],


            ['Liberia', 'LR', 'https://www.countryflags.io/LR/flat/24.png'],
            ['Lesotho', 'LS', 'https://www.countryflags.io/LS/flat/24.png'],
            ['Lithuania', 'LT', 'https://www.countryflags.io/LT/flat/24.png'],
            ['Luxembourg', 'LU', 'https://www.countryflags.io/LU/flat/24.png'],
            ['Latvia', 'LV', 'https://www.countryflags.io/LV/flat/24.png'],
            ['Libya', 'LY', 'https://www.countryflags.io/LY/flat/24.png'],
            ['Morocco', 'MA', 'https://www.countryflags.io/MA/flat/24.png'],
            ['Monaco', 'MC', 'https://www.countryflags.io/MC/flat/24.png'],
            ['Moldova, Republic of', 'MD', 'https://www.countryflags.io/MD/flat/24.png'],
            ['Montenegro', 'ME', 'https://www.countryflags.io/ME/flat/24.png'],
            ['Saint Martin', 'MF', 'https://www.countryflags.io/MF/flat/24.png'],
            ['Madagascar', 'MG', 'https://www.countryflags.io/MG/flat/24.png'],
            ['Marshall Islands', 'MH', 'https://www.countryflags.io/MH/flat/24.png'],
            ['Macedonia, the Former Yugoslav Republic Of', 'MK', 'https://www.countryflags.io/MK/flat/24.png'],
            ['Mali', 'ML', 'https://www.countryflags.io/ML/flat/24.png'],

            ['Myanmar', 'MM', 'https://www.countryflags.io/MM/flat/24.png'],
            ['Mongolia', 'MN', 'https://www.countryflags.io/MN/flat/24.png'],
            ['Macao', 'MO', 'https://www.countryflags.io/MO/flat/24.png'],
            ['Northern Mariana Islands', 'MP', 'https://www.countryflags.io/MP/flat/24.png'],
            ['Martinique', 'MQ', 'https://www.countryflags.io/MQ/flat/24.png'],
            ['Mauritania', 'MR', 'https://www.countryflags.io/MR/flat/24.png'],
            ['Montserrat', 'MS', 'https://www.countryflags.io/MS/flat/24.png'],
            ['Malta', 'MT', 'https://www.countryflags.io/MT/flat/24.png'],
            ['Mauritius', 'MU', 'https://www.countryflags.io/MU/flat/24.png'],
            ['Maldives', 'MV', 'https://www.countryflags.io/MV/flat/24.png'],
            ['Malawi', 'MW', 'https://www.countryflags.io/MW/flat/24.png'],
            ['Mexico', 'MX', 'https://www.countryflags.io/MX/flat/24.png'],
            ['Malaysia', 'MY', 'https://www.countryflags.io/MY/flat/24.png'],
            ['Mozambique', 'MZ', 'https://www.countryflags.io/MZ/flat/24.png'],
            ['Namibia', 'NA', 'https://www.countryflags.io/NA/flat/24.png'],
            ['New Caledonia', 'NC', 'https://www.countryflags.io/NC/flat/24.png'],
            ['Niger', 'NE', 'https://www.countryflags.io/NE/flat/24.png'],
            ['Norfolk Island', 'NF', 'https://www.countryflags.io/NF/flat/24.png'],
            ['Nigeria', 'NG', 'https://www.countryflags.io/NG/flat/24.png'],
            ['Nicaragua', 'NI', 'https://www.countryflags.io/NI/flat/24.png'],
            ['Netherlands', 'NL', 'https://www.countryflags.io/NL/flat/24.png'],
            ['Norway', 'NO', 'https://www.countryflags.io/NO/flat/24.png'],
            ['Nepal', 'NP', 'https://www.countryflags.io/NP/flat/24.png'],
            ['Nauru', 'NR', 'https://www.countryflags.io/NR/flat/24.png'],
            ['Niue', 'NU', 'https://www.countryflags.io/NU/flat/24.png'],
            ['', 'NY', 'https://www.countryflags.io/NY/flat/24.png'],

            ['New Zealand', 'NZ', 'https://www.countryflags.io/NZ/flat/24.png'],
            ['Oman', 'OM', 'https://www.countryflags.io/OM/flat/24.png'],
            ['Panama', 'PA', 'https://www.countryflags.io/PA/flat/24.png'],
            ['Peru', 'PE', 'https://www.countryflags.io/PE/flat/24.png'],
            ['French Polynesia', 'PF', 'https://www.countryflags.io/PF/flat/24.png'],
            ['Papua New Guinea', 'PG', 'https://www.countryflags.io/PG/flat/24.png'],
            ['Philippines', 'PH', 'https://www.countryflags.io/PH/flat/24.png'],
            ['Pakistan', 'PK', 'https://www.countryflags.io/PK/flat/24.png'],
            ['Poland', 'PL', 'https://www.countryflags.io/PL/flat/24.png'],
            ['Saint Pierre And Miquelon', 'PM', 'https://www.countryflags.io/PM/flat/24.png'],
            ['Pitcairn', 'PN', 'https://www.countryflags.io/PN/flat/24.png'],
            ['Puerto Rico', 'PR', 'https://www.countryflags.io/PR/flat/24.png'],
            ['Palestine, State of', 'PS', 'https://www.countryflags.io/PS/flat/24.png'],
            ['Portugal', 'PT', 'https://www.countryflags.io/PT/flat/24.png'],
            ['Palau', 'PW', 'https://www.countryflags.io/PW/flat/24.png'],
            ['Paraguay', 'PY', 'https://www.countryflags.io/PY/flat/24.png'],
            ['Qatar', 'QA', 'https://www.countryflags.io/QA/flat/24.png'],
            ['Réunion', 'RE', 'https://www.countryflags.io/RE/flat/24.png'],
            ['Romania', 'RO', 'https://www.countryflags.io/RO/flat/24.png'],
            ['Serbia', 'RS', 'https://www.countryflags.io/RS/flat/24.png'],
            ['Russian Federation', 'RU', 'https://www.countryflags.io/RU/flat/24.png'],
            ['Rwanda', 'RW', 'https://www.countryflags.io/RW/flat/24.png'],
            ['Saudi Arabia', 'SA', 'https://www.countryflags.io/SA/flat/24.png'],
            ['Solomon Islands', 'SB', 'https://www.countryflags.io/SB/flat/24.png'],
            ['Seychelles', 'SC', 'https://www.countryflags.io/SC/flat/24.png'],
            ['Sudan', 'SD', 'https://www.countryflags.io/SD/flat/24.png'],
            ['Sweden', 'SE', 'https://www.countryflags.io/SE/flat/24.png'],
            ['Singapore', 'SG', 'https://www.countryflags.io/SG/flat/24.png'],
            ['Saint Helena', 'SH', 'https://www.countryflags.io/SH/flat/24.png'],
            ['Slovenia', 'SI', 'https://www.countryflags.io/SI/flat/24.png'],
            ['Svalbard And Jan Mayen', 'SJ', 'https://www.countryflags.io/SJ/flat/24.png'],
            ['Slovakia', 'SK', 'https://www.countryflags.io/SK/flat/24.png'],
            ['Sierra Leone', 'SL', 'https://www.countryflags.io/SL/flat/24.png'],
            ['San Marino', 'SM', 'https://www.countryflags.io/SM/flat/24.png'],
            ['Senegal', 'SN', 'https://www.countryflags.io/SN/flat/24.png'],
            ['Somalia', 'SO', 'https://www.countryflags.io/SO/flat/24.png'],
            ['Suriname', 'SR', 'https://www.countryflags.io/SR/flat/24.png'],
            ['South Sudan', 'SS', 'https://www.countryflags.io/SS/flat/24.png'],
            ['Sao Tome and Principe', 'ST', 'https://www.countryflags.io/ST/flat/24.png'],
            ['El Salvador', 'SV', 'https://www.countryflags.io/SV/flat/24.png'],
            ['Sint Maarten', 'SX', 'https://www.countryflags.io/SX/flat/24.png'],
            ['Syrian Arab Republic', 'SY', 'https://www.countryflags.io/SY/flat/24.png'],
            ['Swaziland', 'SZ', 'https://www.countryflags.io/SZ/flat/24.png'],
            ['Turks and Caicos Islands', 'TC', 'https://www.countryflags.io/TC/flat/24.png'],
            ['Chad', 'TD', 'https://www.countryflags.io/TD/flat/24.png'],
            ['French Southern Territories', 'TF', 'https://www.countryflags.io/TF/flat/24.png'],
            ['Togo', 'TG', 'https://www.countryflags.io/TG/flat/24.png'],
            ['Thailand', 'TH', 'https://www.countryflags.io/TH/flat/24.png'],
            ['Tajikistan', 'TJ', 'https://www.countryflags.io/TJ/flat/24.png'],
            ['Tokelau', 'TK', 'https://www.countryflags.io/TK/flat/24.png'],
            ['Timor-Leste', 'TL', 'https://www.countryflags.io/TL/flat/24.png'],
            ['Turkmenistan', 'TM', 'https://www.countryflags.io/TM/flat/24.png'],
            ['Tunisia', 'TN', 'https://www.countryflags.io/TN/flat/24.png'],
            ['Tonga', 'TO', 'https://www.countryflags.io/TO/flat/24.png'],


            ['Turkey', 'TR', 'https://www.countryflags.io/TR/flat/24.png'],
            ['Trinidad and Tobago', 'TT', 'https://www.countryflags.io/TT/flat/24.png'],
            ['Tuvalu', 'TV', 'https://www.countryflags.io/TV/flat/24.png'],
            ['Taiwan, Republic Of China', 'TW', 'https://www.countryflags.io/TW/flat/24.png'],
            ['Tanzania, United Republic of', 'TZ', 'https://www.countryflags.io/TZ/flat/24.png'],
            ['Ukraine', 'UA', 'https://www.countryflags.io/UA/flat/24.png'],
            ['Uganda', 'UG', 'https://www.countryflags.io/UG/flat/24.png'],
            ['United States Minor Outlying Islands', 'UM', 'https://www.countryflags.io/UM/flat/24.png'],
            ['United States', 'US', 'https://www.countryflags.io/US/flat/24.png'],
            ['Uruguay', 'UY', 'https://www.countryflags.io/UY/flat/24.png'],
            ['Uzbekistan', 'UZ', 'https://www.countryflags.io/UZ/flat/24.png'],
            ['Holy See (Vatican City State)', 'VA', 'https://www.countryflags.io/VA/flat/24.png'],
            ['Saint Vincent And The Grenadines', 'VC', 'https://www.countryflags.io/VC/flat/24.png'],
            ['Venezuela, Bolivarian Republic of', 'VE', 'https://www.countryflags.io/VE/flat/24.png'],
            ['Virgin Islands, British', 'VG', 'https://www.countryflags.io/VG/flat/24.png'],
            ['Virgin Islands, U.S.', 'VI', 'https://www.countryflags.io/VI/flat/24.png'],
            ['Vanuatu', 'VU', 'https://www.countryflags.io/VU/flat/24.png'],
            ['Wallis and Futuna', 'WF', 'https://www.countryflags.io/WF/flat/24.png'],
            ['Samoa', 'WS', 'https://www.countryflags.io/WS/flat/24.png'],
            ['', 'XK', 'https://www.countryflags.io/XK/flat/24.png'],

            ['Yemen', 'YE', 'https://www.countryflags.io/YE/flat/24.png'],
            ['Mayotte', 'YT', 'https://www.countryflags.io/YT/flat/24.png'],
            ['South Africa', 'ZA', 'https://www.countryflags.io/ZA/flat/24.png'],
            ['Zambia', 'ZM', 'https://www.countryflags.io/ZM/flat/24.png'],
            ['Zimbabwe', 'ZW', 'https://www.countryflags.io/ZW/flat/24.png'],
        ];

        foreach (collect($availableTags) as $flag_url){
            $flag = new Flag();
            $flag->name = $flag_url[0];
            $flag->code = $flag_url[1];
            $flag->url = $flag_url[2];
            $flag->save();
        }
    }
}
